import { SPACING } from '@/services/constants/common';

export const HOME = {
  FEATURED_COUNT: 5,
  FEATURED_CARD: {
    WIDTH: 235,
    HEIGHT: 352,
    BORDER_RADIUS: 12,
  },
  REGULAR_CARD: {
    WIDTH: 160,
    HEIGHT: 254,
    GAP: 8,
  },
  GRID_CARD: {
    WIDTH: 177,
    HEIGHT: 236,
    GAP: 8,
  },
  SCROLL: {
    ITEMS_TO_SCROLL: 2,
    CARD_WIDTH: 160,
    CARD_GAP: 8,
    SCROLL_OFFSET: (160 + 8) * 2,
  },
  STYLES: {
    GRID_PADDING_LEFT: 20,
    GRID_PADDING_RIGHT: SPACING.MD,
    FEATURED_CARD_CONTENT_BOTTOM: -10,
    RANK_OVERLAY_PADDING_TOP: 30,
    RANK_OVERLAY_HEIGHT: 220,
    RANK_GRADIENT_WIDTH: 146.47,
    RANK_GRADIENT_HEIGHT: 180,
    RANK_TEXT_FONT_SIZE: 146.47,
    RANK_TEXT_LINE_HEIGHT: 220,
    RANK_TEXT_FONT_WEIGHT: '800' as const,
    BADGE_PADDING_VERTICAL: 2,
    BADGE_BORDER_RADIUS: 4,
    BADGE_FONT_SIZE: 9,
    SPEAKER_ICON_TOP: 6,
    SPEAKER_ICON_RIGHT: 6,
    SPEAKER_ICON_WIDTH: 28,
    SPEAKER_ICON_HEIGHT: 28,
    SPEAKER_ICON_BORDER_RADIUS: 6,
    SPEAKER_ICON_GAP: 7,
    SPEAKER_ICON_IMAGE_WIDTH: 17,
    SPEAKER_ICON_IMAGE_HEIGHT: 17,
  },
} as const;

