export const CARD = {
  REGULAR: {
    WIDTH: 160,
    HEIGHT: 254,
    BORDER_RADIUS: 8,
    GAP: 8,
  },
  IMAGE: {
    WIDTH: 160,
    HEIGHT: 213,
    BORDER_RADIUS: 12,
  },
  GRID: {
    WIDTH: 177,
    HEIGHT: 236,
  },
  STYLES: {
    TITLE_FONT_SIZE: 14,
    TITLE_LINE_HEIGHT: 18,
    SUBTITLE_FONT_SIZE: 9,
    WATCH_CONTAINER_BOTTOM_OFFSET: 8,
    WATCH_CONTAINER_RIGHT_OFFSET: 8,
    WATCH_CONTAINER_PADDING_HORIZONTAL: 6,
    WATCH_CONTAINER_PADDING_VERTICAL: 4,
    WATCH_CONTAINER_BORDER_RADIUS: 16,
    EYE_ICON_WIDTH: 12,
    EYE_ICON_HEIGHT: 12,
    EYE_ICON_MARGIN_RIGHT: 4,
    GRID_BORDER_RADIUS: 8,
  },
} as const;

