export const EXPLORE_MORE_CARD = {
  WIDTH: 177,
  HEIGHT: 236,
  BORDER_RADIUS: 8,
} as const;

export const CARD_WIDTH = EXPLORE_MORE_CARD.WIDTH;
export const CARD_HEIGHT = EXPLORE_MORE_CARD.HEIGHT;
export const CARD_BORDER_RADIUS = EXPLORE_MORE_CARD.BORDER_RADIUS;