import {StyleSheet} from 'react-native';
import {COLORS, SPACING, scaleWidth, scaleHeight, DIMENSIONS} from '@/services/constants/common';
import {TYPOGRAPHY} from '@/services/constants/typography';
import {FEED} from '../../constants';

const SCREEN_WIDTH = DIMENSIONS.SCREEN.WIDTH;
const CARD_WIDTH = SCREEN_WIDTH;
const CARD_HEIGHT = FEED.DIMENSIONS.ITEM_HEIGHT;
const CONTENT_BOTTOM_OFFSET = scaleHeight(FEED.FEED_ITEM.CONTENT_BOTTOM_OFFSET);

export const styles = StyleSheet.create({
  card: {
    width: CARD_WIDTH,
    backgroundColor: COLORS.BACKGROUND,
    overflow: 'hidden',
  },
  image: {
    width: CARD_WIDTH,
    resizeMode: 'cover',
    position: 'absolute',
    top: 0,
    left: 0,
    zIndex: 1,
    elevation: 1,
  },
  backButton: {
    position: 'absolute',
    top: scaleHeight(FEED.STYLES.BACK_BUTTON_TOP),
    left: SPACING.MD,
    zIndex: 10,
    elevation: 10,
    width: FEED.STYLES.BACK_ICON_SIZE,
    height: FEED.STYLES.BACK_ICON_SIZE,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backIcon: {
    width: FEED.STYLES.BACK_ICON_SIZE,
    height: FEED.STYLES.BACK_ICON_SIZE,
    tintColor: COLORS.PRIMARY_TEXT,
  },
  sideIconButton: {
    alignItems: 'center',
    gap: SPACING.XS,
  },
  sideIcon: {
    width: FEED.STYLES.SIDE_ICON_SIZE,
    height: FEED.STYLES.SIDE_ICON_SIZE,
    tintColor: COLORS.PRIMARY_TEXT,
  },
  sideIconSmall: {
    width: FEED.STYLES.SIDE_ICON_SMALL_SIZE,
    height: FEED.STYLES.SIDE_ICON_SMALL_SIZE,
    tintColor: COLORS.PRIMARY_TEXT,
  },
  sideIconText: {
    ...TYPOGRAPHY.SUBTITLE,
    color: COLORS.PRIMARY_TEXT,
    textAlign: 'center',
  },
  content: {
    position: 'absolute',
    bottom: CONTENT_BOTTOM_OFFSET,
    left: 0,
    right: 0,
    padding: SPACING.MD,
    paddingBottom: SPACING.MD + 10,
    justifyContent: 'flex-end',
    height: scaleHeight(279),
    zIndex: 3,
    elevation: 3,
    backgroundColor: COLORS.TRANSPARENT,
    overflow: 'visible',
  },
  contentRow: {
    flexDirection: 'row',
    gap: SPACING.MD,
    alignItems: 'flex-end',
    position: 'relative',
  },
  textContent: {
    flex: 1,
    paddingRight: scaleWidth(80),
  },
  sideIcons: {
    alignItems: 'center',
    gap: SPACING.LG,
    position: 'absolute',
    right: SPACING.MD,
    bottom: CONTENT_BOTTOM_OFFSET + scaleHeight(20),
    zIndex: 10,
    elevation: 10,
  },
  title: {
    ...TYPOGRAPHY.HEADING,
    letterSpacing: 0.2,
    color: COLORS.PRIMARY_TEXT,
    marginTop: SPACING.SM,
    position: 'relative',
    zIndex: 1,
  },
  descriptionContainer: {
    marginTop: SPACING.SM,
    position: 'relative',
    zIndex: 1,
  },
  actionsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: SPACING.MD,
    paddingTop: SPACING.MD,
    zIndex: 4,
    elevation: 4,
    position: 'relative',
  },
  watchNowButton: {
    backgroundColor: COLORS.WATCH_NOW_BUTTON,
    width: scaleWidth(301),
    height: 44,
    borderRadius: 16,
    paddingTop: 6,
    paddingRight: 20,
    paddingBottom: 6,
    paddingLeft: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    maxWidth: 301,
    zIndex: 5,
    elevation: 5,
  },
  playIcon: {
    width: 16,
    height: 16,
    tintColor: COLORS.PRIMARY_TEXT,
  },
  watchNowText: {
    ...TYPOGRAPHY.BUTTON,
    color: COLORS.PRIMARY_TEXT,
    textAlign: 'center',
  },
  shareButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  shareIcon: {
    fontSize: 24,
    color: COLORS.PRIMARY_TEXT,
  },
  moreIcon: {
    width: 24,
    height: 24,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 4,
  },
  moreDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: COLORS.PRIMARY_TEXT,
  },
  video: {
    width: CARD_WIDTH,
    backgroundColor: COLORS.BLACK,
    position: 'absolute',
    top: 0,
    left: 0,
    zIndex: 1,
    elevation: 1,
  },
  videoPressArea: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 6,
    elevation: 6,
  },
  videoPressAreaTop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: scaleHeight(279) + CONTENT_BOTTOM_OFFSET,
    zIndex: 6,
    elevation: 6,
  },
  playButtonOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 7,
    elevation: 7,
  },
  playButtonIcon: {
    width: 64,
    height: 64,
    tintColor: COLORS.WHITE,
    opacity: 0.3,
  },
});

