import { Dimensions } from 'react-native';
import {API_BASE_URL} from '../config/env';

const DESIGN_WIDTH = 393;
const DESIGN_HEIGHT = 852;

export const { width: DEVICE_WIDTH, height: DEVICE_HEIGHT } = Dimensions.get('window');
export const isIPad = DEVICE_WIDTH >= 768;
export const FEATURED_COUNT = 5;


export const scaleWidth = (size: number): number => {
  return (size / DESIGN_WIDTH) * DEVICE_WIDTH;
};

export const scaleHeight = (size: number): number => {
  return (size / DESIGN_HEIGHT) * DEVICE_HEIGHT;
};

export const BOTTOM_TAB_BAR_HEIGHT = 60;

export const API_ENDPOINTS = {
  HOME_PAGE: `${API_BASE_URL}/homePage.json`,
  FEED_PAGE: `${API_BASE_URL}/FeedPage1.json`,
};

export const COLORS = {
  BACKGROUND: '#0E0E0E',
  PRIMARY_TEXT: '#FEFEFE',
  SECONDARY_TEXT: '#FFFFFF99',
  WATCH_NOW_BUTTON: '#F6245A',
  CARD_BACKGROUND: '#0E0E0ECC',
  OVERLAY_BACKGROUND: '#0E0E0E33',
  WHITE: '#FFFFFF',
};

export const SPACING = {
  BASE: 16,
  XS: 4,
  SM: 8,
  MD: 14,
  LG: 24,
  XL: 32,
  XXL: 48,
};

export const TYPOGRAPHY = {
  CARD_TITLE: {
    fontFamily: 'Inter',
    fontWeight: '600',
    fontSize: 20,
    lineHeight: 28,
    letterSpacing: 0.01,
  },
  CARD_SUBTITLE: {
    fontFamily: 'Inter',
    fontWeight: '400',
    fontSize: 11,
    lineHeight: 11,
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  LABEL: {
    fontFamily: 'Inter',
    fontWeight: '700',
    fontSize: 11,
    lineHeight: 11,
    letterSpacing: 0,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
};

export const DIMENSIONS = {
  FEED_ITEM: {
    WIDTH: 393,
    HEIGHT: 764,
  },
  DESIGN_BASE: {
    WIDTH: DESIGN_WIDTH,
    HEIGHT: DESIGN_HEIGHT,
  },
  DEVICE: {
    WIDTH: DEVICE_WIDTH,
    HEIGHT: DEVICE_HEIGHT,
  },
  SCREEN: {
    WIDTH: DEVICE_WIDTH,
    HEIGHT: DEVICE_HEIGHT,
  },
  FEED: {
    ASPECT_RATIO: 764 / 393,
    ITEM_HEIGHT: Math.min((DEVICE_WIDTH * 764) / 393, DEVICE_HEIGHT),
    IS_IPAD: DEVICE_WIDTH >= 768,
  },
  CARD: {
    REGULAR: {
      WIDTH: 160,
      HEIGHT: 254,
      BORDER_RADIUS: 8,
      GAP: 8,
    },
    IMAGE: {
      WIDTH: 160,
      HEIGHT: 213,
      BORDER_RADIUS: 12,
    },
    GRID: {
      WIDTH: 177,
      HEIGHT: 236,
      BORDER_RADIUS: 8,
      GAP: 8,
    },
    FEATURED: {
      WIDTH: 235,
      HEIGHT: 352,
      BORDER_RADIUS: 12,
    },
    EXPLORE_MORE: {
      WIDTH: 177,
      HEIGHT: 236,
      BORDER_RADIUS: 8,
    },
    FEED: {
      BORDER_RADIUS: 0,
      CONTENT_BOTTOM_OFFSET: 0,
    },
  },
  SCROLL: {
    ITEMS_TO_SCROLL: 2,
    CARD_WIDTH: 160,
    CARD_GAP: 8,
  },
};

export const SCROLL_CONSTANTS = {
  ITEMS_TO_SCROLL: DIMENSIONS.SCROLL.ITEMS_TO_SCROLL,
  SCROLL_OFFSET: (DIMENSIONS.SCROLL.CARD_WIDTH + DIMENSIONS.SCROLL.CARD_GAP) * DIMENSIONS.SCROLL.ITEMS_TO_SCROLL,
};

export const STYLE_CONSTANTS = {
  GRID_PADDING_LEFT: 20,
  GRID_PADDING_RIGHT: SPACING.MD,
  SECTION_TITLE_FONT_SIZE: 20,
  SECTION_TITLE_LINE_HEIGHT: 28,
  SECTION_TITLE_LETTER_SPACING: 0.2,
  SECTION_TITLE_FONT_WEIGHT: '600',
  ERROR_TEXT_FONT_SIZE: 16,
  OVERLAY_OPACITY: 0.4,
  FEATURED_CARD_CONTENT_BOTTOM: -10,
  RANK_OVERLAY_PADDING_TOP: 30,
  RANK_OVERLAY_HEIGHT: 220,
  RANK_GRADIENT_WIDTH: 146.47,
  RANK_GRADIENT_HEIGHT: 180,
  RANK_TEXT_FONT_SIZE: 146.47,
  RANK_TEXT_LINE_HEIGHT: 220,
  RANK_TEXT_FONT_WEIGHT: '800',
  BADGE_PADDING_VERTICAL: 2,
  BADGE_BORDER_RADIUS: 4,
  BADGE_FONT_SIZE: 9,
  SPEAKER_ICON_TOP: 6,
  SPEAKER_ICON_RIGHT: 6,
  SPEAKER_ICON_WIDTH: 28,
  SPEAKER_ICON_HEIGHT: 28,
  SPEAKER_ICON_BORDER_RADIUS: 6,
  SPEAKER_ICON_GAP: 7,
  SPEAKER_ICON_IMAGE_WIDTH: 17,
  SPEAKER_ICON_IMAGE_HEIGHT: 17,
  WATCH_CONTAINER_BOTTOM_OFFSET: 8,
  WATCH_CONTAINER_RIGHT_OFFSET: 8,
  WATCH_CONTAINER_PADDING_HORIZONTAL: 6,
  WATCH_CONTAINER_PADDING_VERTICAL: 4,
  WATCH_CONTAINER_BORDER_RADIUS: 16,
  EYE_ICON_WIDTH: 12,
  EYE_ICON_HEIGHT: 12,
  EYE_ICON_MARGIN_RIGHT: 4,
  CARD_TITLE_FONT_SIZE: 14,
  CARD_TITLE_LINE_HEIGHT: 18,
  CARD_SUBTITLE_FONT_SIZE: 9,
  GRID_BORDER_RADIUS: 8,
  FEED_BACK_BUTTON_TOP: 66,
  FEED_BACK_ICON_SIZE: 24,
  FEED_SIDE_ICON_SIZE: 36,
  FEED_SIDE_ICON_SMALL_SIZE: 24,
  FEED_SIDE_ICON_TEXT_FONT_SIZE: 11,
  FEED_SIDE_ICON_TEXT_LINE_HEIGHT: 14,
  FEED_CONTENT_PADDING_BOTTOM_EXTRA: 10,
  FEED_CONTENT_HEIGHT: 279,
  FEED_TEXT_CONTENT_PADDING_RIGHT: 80,
  FEED_TITLE_FONT_SIZE: 20,
  FEED_TITLE_LINE_HEIGHT: 28,
  FEED_TITLE_LETTER_SPACING: 0.2,
  FEED_TITLE_FONT_WEIGHT: '600',
  FEED_WATCH_BUTTON_WIDTH: 301,
  FEED_WATCH_BUTTON_HEIGHT: 44,
  FEED_WATCH_BUTTON_BORDER_RADIUS: 16,
  FEED_WATCH_BUTTON_PADDING_TOP: 6,
  FEED_WATCH_BUTTON_PADDING_RIGHT: 20,
  FEED_WATCH_BUTTON_PADDING_BOTTOM: 6,
  FEED_WATCH_BUTTON_PADDING_LEFT: 16,
  FEED_WATCH_BUTTON_GAP: 4,
  FEED_PLAY_ICON_SIZE: 16,
  FEED_WATCH_TEXT_FONT_SIZE: 14,
  FEED_WATCH_TEXT_FONT_WEIGHT: '600',
  FEED_SHARE_BUTTON_SIZE: 40,
  FEED_SHARE_ICON_FONT_SIZE: 24,
  FEED_MORE_ICON_SIZE: 24,
  FEED_MORE_ICON_GAP: 4,
  FEED_MORE_DOT_SIZE: 4,
  FEED_MORE_DOT_BORDER_RADIUS: 2,
  TAB_BAR_FONT_SIZE: 10,
  TAB_BAR_FONT_WEIGHT: '500',
  TAB_BAR_HEIGHT: 60,
  TAB_BAR_BORDER_WIDTH: 1,
};

