import { DEVICE_WIDTH, DEVICE_HEIGHT } from '@/services/constants/common';

export const FEED_CONSTANTS = {
  VIDEO_CONTROL: {
    PLAY_DELAY: 30,
    HOME_PREVIEW: {
      INITIAL_DELAY: 100,
      RETRY_DELAY: 100,
      PREVIEW_DURATION: 150,
      RETRY_PAUSE_DELAY: 50,
    },
    APP_STATE: {
      RESTORE_DELAY: 200,
    },
    FOCUS_EFFECT: {
      DELAY: 100,
    },
  },
  FEED_ITEM: {
    AUTO_PLAY_DELAY: 100,
    TITLE_NUMBER_OF_LINES: 2,
    WIDTH: 393,
    HEIGHT: 764,
    CONTENT_HEIGHT: 279,
    CONTENT_BOTTOM_OFFSET: 0,
  },
  DIMENSIONS: {
    ASPECT_RATIO: 764 / 393,
    ITEM_HEIGHT: Math.min((DEVICE_WIDTH * 764) / 393, DEVICE_HEIGHT),
  },
  STYLES: {
    BACK_BUTTON_TOP: 66,
    BACK_ICON_SIZE: 24,
    SIDE_ICON_SIZE: 36,
    SIDE_ICON_SMALL_SIZE: 24,
    SIDE_ICON_TEXT_FONT_SIZE: 11,
    SIDE_ICON_TEXT_LINE_HEIGHT: 14,
    CONTENT_PADDING_BOTTOM_EXTRA: 10,
    CONTENT_HEIGHT: 279,
    TEXT_CONTENT_PADDING_RIGHT: 80,
    TITLE_FONT_SIZE: 20,
    TITLE_LINE_HEIGHT: 28,
    TITLE_LETTER_SPACING: 0.2,
    TITLE_FONT_WEIGHT: '600',
    WATCH_BUTTON_WIDTH: 301,
    WATCH_BUTTON_HEIGHT: 44,
    WATCH_BUTTON_BORDER_RADIUS: 16,
    WATCH_BUTTON_PADDING_TOP: 6,
    WATCH_BUTTON_PADDING_RIGHT: 20,
    WATCH_BUTTON_PADDING_BOTTOM: 6,
    WATCH_BUTTON_PADDING_LEFT: 16,
    WATCH_BUTTON_GAP: 4,
    PLAY_ICON_SIZE: 16,
    WATCH_TEXT_FONT_SIZE: 14,
    WATCH_TEXT_FONT_WEIGHT: '600',
    SHARE_BUTTON_SIZE: 40,
    SHARE_ICON_FONT_SIZE: 24,
    MORE_ICON_SIZE: 24,
    MORE_ICON_GAP: 4,
    MORE_DOT_SIZE: 4,
    MORE_DOT_BORDER_RADIUS: 2,
  },
  VIEWABILITY: {
    ITEM_VISIBLE_PERCENT_THRESHOLD: 50,
    MINIMUM_VIEW_TIME: 100,
  },
  FLATLIST: {
    END_REACHED_THRESHOLD: 0.5,
    MAX_TO_RENDER_PER_BATCH: 3,
    INITIAL_NUM_TO_RENDER: 3,
    WINDOW_SIZE: 3,
    SCROLL_EVENT_THROTTLE: 16,
  },
  ARRAY: {
    FIRST_ITEM_INDEX: 0,
    EMPTY_LENGTH: 0,
  },
} as const;

